### ISSUE TITLE
Rango máximo no esta bien calculado

### ISSUE THREAD

**Issue by dlitvakb** [gmbarrera/BattleField-AI#5]
https://github.com/gmbarrera/BattleField-AI/blob/master/src/ia/battle/camp/Warrior.java#L83

```java
int maxRange = Math.min(ConfigurationManager.getInstance().getMapHeight(), ConfigurationManager.getInstance().getMapHeight());
```

Deberia utilizar tanto el alto como el ancho del mapa, no solo el alto.

Hay una función ya definida en `ConfigurationManager`

```java
int maxRange = ConfigurationManager.getInstance().getMaxRangeForWarrior()
```

**Comment by gmbarrera** [comment]
Ok. Cambiado.
